import type { StoryObj } from '@storybook/react';
declare const meta: any;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Primary: Story;
export declare const Secondary: Story;
export declare const Destructive: Story;
export declare const Outline: Story;
export declare const Ghost: Story;
export declare const Link: Story;
